### PR TITLE
Idea: Use Webdriver instead of Phantom

### PR DESCRIPTION
**Pull request by Strajk**
Hi there, I really like this project...

I needed to use Chrome instead of PhantomJS, as it renders a page a lot differently (even when using PhantomJS 2), so I swapped Phantom to neutral Webdriver which can communicate with any browser - Chrome, Firefox and even PhantomJS – but I can make a choice :)

I'm really not happy with my code, but I'm really not good with browser automation. But it's doing what it should do, so I'm making this PR not with intent to merge it, but to discuss it or maybe somebody can help me with a correct implementation.

Biggest ugliness is IMHO dep on easyimage, as Chrome is not able to resize below 400px (https://code.google.com/p/chromium/issues/detail?id=275686), only with use of mobileEmulation, which causes screenshots to contain crazy amount of whitespace.

mobile

### CODE REVIEW

**Comment by fabrik42** [comment]
Hello Pavel,

first of all, thank you very much for trying out my script and providing feedback, I really appreciate this.

Before I wrote this script, I already tried out several alternatives and the main point of this script was to keep it as easy and accessible as possible. You basically just have to `brew install phantomjs` and you're ready to go.

If we would switch to webdriver this would be much more complicated. You need:
- node.js and npm dependencies (and what about io.js?)
- Java
- A Selenium server running (and way to configure e.g. the port)
- A proper configured imagemagick installation (and again, probably more configuration options)

I see the advantages of your solution, but I don't want to introduce this much complexity into the setup and configuration of the script.

I think it's great that you took the time to evaluate another option, but I don't want to trade in the simplicity of the script for this features.

However, I would be very interested to hear about the problems you were facing using PhantomJS. Could you provide some screenshots, expected vs. result?

**Comment by Strajk** [comment]
Hi, thanks for taking time,

I really like the idea of simplicify, I wish sooo much it would just work  :) I totally, agree with complexity, I thought I would take me half an hour to ajdust your script to work with Webdriver, but spend another few hours figuring out how to handle different behavour with different browsers (like being unable to make Chrome window narrower and cropping the image instead)

Posting images why PhantomJS was, sadly, unusable for me:

PhantomJS 2 on the left, Chrome on the right.

desktop

mobile

**Comment by fabrik42** [comment]
It looks like PhantomJS is using another font family to render the text.
Do you use special webfonts? How do you include them (Google Web Fonts, local file)?

**Comment by Strajk** [comment]
Just plain `font-family: sans-serif;`, you can check it live at https://en.skypicker.com

But that's not an issue of this project, but ours with compatibity and Phantom's with rendering :)

Thanks for your time!

**Comment by fabrik42** [comment]
I think the problem could be that you're only specifying a generic font family. This basically leaves the choice of the used font up to the browser. So your website is probably going to be rendered in Helvetica on OSX, Arial on Windows and something like Bitstream Vera on Linux.

You could try to use a font stack like `font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;` and see what happens.

**Comment by fabrik42** [comment]
Closing this for now - please reopen if there is something new.

**Pull request closed without merging**
